version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    container_name: malaria-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    
  redis:
    image: redis:7-alpine
    container_name: malaria-redis
    ports:
      - "6379:6379"
    
  backend:
    build: ./server
    container_name: malaria-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/malaria_lab
    depends_on:
      - mongodb
      - redis
    
  frontend:
    build: ./client
    container_name: malaria-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongodb_data: